create extension if not exists "pgcrypto";

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null unique,
  logo_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  requirements text not null,
  location text not null,
  company_id bigint not null references public.companies(id) on delete cascade,
  recruiter_id text not null,
  "isOpen" boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.saved_jobs (
  id bigint generated by default as identity primary key,
  user_id text not null,
  job_id bigint not null references public.jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, job_id)
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  candidate_id text not null,
  name text not null,
  experience integer not null default 0,
  skills text not null,
  education text not null,
  resume text not null,
  status text not null default 'applied',
  created_at timestamptz not null default now(),
  constraint applications_status_check check (status in ('applied', 'interviewing', 'hired', 'rejected'))
);

insert into public.companies (name, logo_url)
values
  ('Amazon', '/companies/amazon.svg'),
  ('Atlassian', '/companies/atlassian.svg'),
  ('Google', '/companies/google.webp'),
  ('IBM', '/companies/ibm.svg'),
  ('Meta', '/companies/meta.svg'),
  ('Microsoft', '/companies/microsoft.webp'),
  ('Netflix', '/companies/netflix.png'),
  ('Uber', '/companies/uber.svg')
on conflict (name) do nothing;

alter table public.companies enable row level security;
alter table public.jobs enable row level security;
alter table public.saved_jobs enable row level security;
alter table public.applications enable row level security;

drop policy if exists "companies_select_authenticated" on public.companies;
create policy "companies_select_authenticated"
on public.companies for select
to authenticated
using (true);

drop policy if exists "companies_insert_authenticated" on public.companies;
create policy "companies_insert_authenticated"
on public.companies for insert
to authenticated
with check (true);

drop policy if exists "jobs_select_authenticated" on public.jobs;
create policy "jobs_select_authenticated"
on public.jobs for select
to authenticated
using (true);

drop policy if exists "jobs_insert_owner" on public.jobs;
create policy "jobs_insert_owner"
on public.jobs for insert
to authenticated
with check (recruiter_id = auth.uid()::text);

drop policy if exists "jobs_update_owner" on public.jobs;
create policy "jobs_update_owner"
on public.jobs for update
to authenticated
using (recruiter_id = auth.uid()::text)
with check (recruiter_id = auth.uid()::text);

drop policy if exists "jobs_delete_owner" on public.jobs;
create policy "jobs_delete_owner"
on public.jobs for delete
to authenticated
using (recruiter_id = auth.uid()::text);

drop policy if exists "saved_jobs_select_owner" on public.saved_jobs;
create policy "saved_jobs_select_owner"
on public.saved_jobs for select
to authenticated
using (user_id = auth.uid()::text);

drop policy if exists "saved_jobs_insert_owner" on public.saved_jobs;
create policy "saved_jobs_insert_owner"
on public.saved_jobs for insert
to authenticated
with check (user_id = auth.uid()::text);

drop policy if exists "saved_jobs_delete_owner" on public.saved_jobs;
create policy "saved_jobs_delete_owner"
on public.saved_jobs for delete
to authenticated
using (user_id = auth.uid()::text);

drop policy if exists "applications_select_candidate_or_recruiter" on public.applications;
create policy "applications_select_candidate_or_recruiter"
on public.applications for select
to authenticated
using (
  candidate_id = auth.uid()::text
  or exists (
    select 1
    from public.jobs
    where jobs.id = applications.job_id
      and jobs.recruiter_id = auth.uid()::text
  )
);

drop policy if exists "applications_insert_candidate" on public.applications;
create policy "applications_insert_candidate"
on public.applications for insert
to authenticated
with check (candidate_id = auth.uid()::text);

drop policy if exists "applications_update_recruiter" on public.applications;
create policy "applications_update_recruiter"
on public.applications for update
to authenticated
using (
  exists (
    select 1
    from public.jobs
    where jobs.id = applications.job_id
      and jobs.recruiter_id = auth.uid()::text
  )
)
with check (
  exists (
    select 1
    from public.jobs
    where jobs.id = applications.job_id
      and jobs.recruiter_id = auth.uid()::text
  )
);

insert into storage.buckets (id, name, public)
values ('company-logo', 'company-logo', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('resumes', 'resumes', true)
on conflict (id) do nothing;

drop policy if exists "company_logo_public_read" on storage.objects;
create policy "company_logo_public_read"
on storage.objects for select
to public
using (bucket_id = 'company-logo');

drop policy if exists "company_logo_authenticated_insert" on storage.objects;
create policy "company_logo_authenticated_insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'company-logo');

drop policy if exists "resumes_public_read" on storage.objects;
create policy "resumes_public_read"
on storage.objects for select
to public
using (bucket_id = 'resumes');

drop policy if exists "resumes_authenticated_insert" on storage.objects;
create policy "resumes_authenticated_insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'resumes');
